'use client'
import { GlobalStyles } from '@/styles/Globals';
import { theme } from '@/styles/Theme';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { ThemeProvider } from 'styled-components';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['500', '600', '700', '800'],
})

export const metadata: Metadata = {
  title: 'Trellix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <ThemeProvider theme={theme}>
        <GlobalStyles />
          <body className={poppins.className}>
            {children}
          </body>
      </ThemeProvider>
    </html>
  )
}
